### ISSUE TITLE
Implement authorization

### ISSUE THREAD

**Issue by sepans** [sepans/ctzen#1]
Using cookies users can answer to a series of questions without being logged-in.

- All answers are saved under the same user profile.
- A user cannot add answer under another user's profile.

### Technical details:
- Upon entering the question answering section for the first time a cookie is added to session.
- cookie toke is sent to graphql with every request
- if cookie doesn't exist in `User` table a new record is created with with that cookie. The answer is saved under that new user.
- else if the cookie exist, the answer is added under matching user

Questions: Should it be confirmed with a returning user with previous answers, if they want to continue? 

### Subtasks:
- [x] Add cookie column to DB.
- [x] Add cookie to session
- [x] Change graphql endpoint for answering question by cookie
- [x] Update UI

**Comment by sepans** [comment]
Fixed.
